#!/bin/sh
case "$1" in
    start)
        echo -n "Starting aesdsocketd: "
        if start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d; then
            echo "OK"
        else
            echo "failed"
        fi
        ;;
    stop)
        echo -n "Stopping aesdsocketd: "
        if start-stop-daemon -K -n aesdsocket; then
            echo "OK"
        else
            echo "failed"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
